#!/usr/bin/env node
// Compiles the FSH IG with Sushi, then copies the generated resource JSON
// into packages/fhir-artifacts/generated/ so every consumer imports the compiled
// artifacts from one place rather than out of an app's source tree.
//
// FSH is the single source of truth for SPiER's FHIR shapes. Anything under
// packages/fhir-artifacts/generated/ is a build artifact — gitignored, regenerated by this
// script via `npm run copy-fhir` (also invoked by `predev` / `prebuild`).
//
// The SUSHI compile is slow (~30s), so this script is incremental: it skips the
// compile when the generated artifacts are already newer than every FSH input
// (see the "Staleness check" section below). `--force` always recompiles.

import { spawnSync } from 'node:child_process'
import { copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { dirname, resolve, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { SUSHI_VERSION } from '../../scripts/lib/sushi-version.mjs'

const scriptPath = fileURLToPath(import.meta.url)
const __dirname = dirname(scriptPath)
const repoRoot = resolve(__dirname, '..', '..')
const igDir = join(repoRoot, 'ig')
const generatedDir = join(igDir, 'fsh-generated', 'resources')
const destDir = join(repoRoot, 'packages', 'fhir-artifacts', 'generated')

// Inputs that determine the SUSHI output. If none of these change, recompiling
// produces byte-identical artifacts (see the staleness check below).
const fshInputDir = join(igDir, 'input', 'fsh')
const sushiConfig = join(igDir, 'sushi-config.yaml')
// Hand-authored Questionnaire JSON. Not a SUSHI input — SUSHI never reads it —
// but it IS an input to `writeInstrumentItemCodes()` below, so editing a
// Questionnaire has to invalidate this script's output. Leaving it out is the
// bug the phase-2 plan flagged in advance: the generated lookup would sit there
// stale while the Questionnaire it was derived from had moved on.
const questionnairesDir = join(repoRoot, 'FHIR-Resources')
// The TypeScript artifacts this script emits.
const carePlanProfilesTsPath = join(destDir, 'care-plan-profiles.generated.ts')
const instrumentSignaturesTsPath = join(destDir, 'instrument-signatures.generated.ts')
const stageIdsTsPath = join(destDir, 'stage-ids.generated.ts')
const generatedTsPaths = [carePlanProfilesTsPath, instrumentSignaturesTsPath, stageIdsTsPath]

// ImplementationGuide is IG manifest metadata, not a domain resource consumed by the app.
const EXCLUDE_PREFIXES = ['ImplementationGuide-']

function log(msg) {
  console.log(`[copy-fhir] ${msg}`)
}

// ---------------------------------------------------------------------------
// Staleness check
// ---------------------------------------------------------------------------
// Why this exists:
//   `predev` runs this script on EVERY `npm run dev`, and the SUSHI FSH compile
//   takes ~30s. But the FSH sources rarely change between dev starts, and SUSHI
//   is deterministic — if no input changed, recompiling produces identical
//   output. So we skip the compile (and the copy) whenever the artifacts the app
//   consumes are already newer than every input that feeds them. This turns the
//   common case (no FSH edits) from a ~30s wait into an instant no-op, while
//   still regenerating automatically the first time after any FSH change.
//
// What counts as an input:
//   - everything under ig/input/fsh/ (the FSH source of truth)
//   - ig/sushi-config.yaml (canonical, version, dependencies — all shape output)
//   - everything under FHIR-Resources/ (the hand-authored Questionnaire JSON that
//     instrument-signatures.generated.ts is derived from). SUSHI does not read
//     this tree, so it was not an input while the only codegen read SUSHI output.
//   - this script itself (its copy/exclude/codegen logic shapes the output too)
//
// What counts as output:
//   - the resource JSON its consumers import (packages/fhir-artifacts/generated/)
//   - the generated TypeScript (care-plan-profiles.generated.ts,
//     instrument-signatures.generated.ts)
//   We deliberately key off these CONSUMED artifacts, not ig/fsh-generated/, so
//   that a cleaned/stale intermediate dir doesn't matter — if the app's inputs
//   are current, there is nothing to do.
//
// Correctness:
//   We skip only when the OLDEST output postdates the NEWEST input, so a single
//   stale output forces a full rebuild. mtime ties (rare, coarse filesystems)
//   resolve toward rebuilding — conservative by design. A fresh clone has no
//   outputs, so the check fails and we build. `--force` bypasses the check
//   entirely; `prebuild` passes it so release builds never trust mtimes.

function walkFiles(dir) {
  const out = []
  let entries
  try {
    entries = readdirSync(dir, { withFileTypes: true })
  } catch {
    return out // missing dir contributes no files
  }
  for (const entry of entries) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) out.push(...walkFiles(full))
    else out.push(full)
  }
  return out
}

function mtimeMs(path) {
  try {
    return statSync(path).mtimeMs
  } catch {
    return null // missing files are ignored by callers
  }
}

function isUpToDate() {
  // Both consumed artifacts must be present, or there is nothing to trust:
  //   - the copied resource dir (must contain files), and
  //   - every generated TS file.
  // Filtering missing paths out of the comparison would let a deleted output
  // (empty destDir, removed generated TS) pass as "up to date" and skip a
  // rebuild the app actually needs — so check existence explicitly first.
  const destFiles = walkFiles(destDir)
  if (destFiles.length === 0) return false // fresh clone / cleaned tree → build

  const tsMtimes = generatedTsPaths.map(mtimeMs)
  if (tsMtimes.some((t) => t === null)) return false // a generated TS deleted → build

  const inputFiles = [
    sushiConfig,
    scriptPath,
    ...walkFiles(fshInputDir),
    ...walkFiles(questionnairesDir),
  ]
  const inputTimes = inputFiles.map(mtimeMs).filter((t) => t !== null)
  // No inputs found is unexpected; rebuild rather than silently skip.
  if (inputTimes.length === 0) return false

  const newestInput = Math.max(...inputTimes)
  const oldestOutput = Math.min(...destFiles.map(mtimeMs), ...tsMtimes)
  return oldestOutput > newestInput
}

function runSushi() {
  log('compiling FSH with sushi...')
  // Pinned to SUSHI_VERSION above rather than resolving whatever `fsh-sushi`
  // npx finds — it is no longer a web/ devDependency, so there is no locked
  // local copy for npx to prefer over the registry. Pass igDir as an argument
  // — sushi treats it as the project folder and writes to ig/fsh-generated/.
  const result = spawnSync('npx', ['-y', `fsh-sushi@${SUSHI_VERSION}`, igDir], {
    stdio: 'inherit',
    shell: process.platform === 'win32',
  })
  if (result.status !== 0) {
    console.error('[copy-fhir] sushi failed — aborting copy')
    process.exit(result.status ?? 1)
  }
}

function clearDest() {
  try {
    rmSync(destDir, { recursive: true, force: true })
  } catch {
    // ignore
  }
  mkdirSync(destDir, { recursive: true })
}

function copyResources() {
  let entries
  try {
    entries = readdirSync(generatedDir)
  } catch (err) {
    console.error(`[copy-fhir] expected ${generatedDir} to exist after sushi; got ${err.message}`)
    process.exit(1)
  }

  let copied = 0
  let skipped = 0
  for (const name of entries) {
    if (!name.endsWith('.json')) continue
    if (EXCLUDE_PREFIXES.some((p) => name.startsWith(p))) {
      skipped += 1
      continue
    }
    const src = join(generatedDir, name)
    if (!statSync(src).isFile()) continue
    copyFileSync(src, join(destDir, name))
    copied += 1
  }
  log(`copied ${copied} resource(s) to packages/fhir-artifacts/generated/ (skipped ${skipped})`)
}

/**
 * Emit a TypeScript file declaring the union of canonical URLs for every
 * SPiER StructureDefinition that constrains CarePlan. The CarePlan mappers
 * use this union to type their `meta.profile` claim — FSH stays the single
 * source of truth.
 */
function writeCarePlanProfileTypes() {
  const sdFiles = readdirSync(destDir).filter(
    (n) => n.startsWith('StructureDefinition-') && n.endsWith('.json'),
  )
  const urls = []
  for (const name of sdFiles) {
    const doc = JSON.parse(readFileSync(join(destDir, name), 'utf8'))
    if (doc.kind === 'resource' && doc.type === 'CarePlan' && typeof doc.url === 'string') {
      urls.push(doc.url)
    }
  }
  urls.sort()

  const outPath = carePlanProfilesTsPath
  const lines = [
    '// Auto-generated by web/scripts/copy-fhir.mjs — do not edit by hand.',
    '// Source: ig/input/fsh/<tool>.fsh (Profile: ... Parent: CarePlan).',
    '// Regenerated on every `npm run copy-fhir` (also runs as predev / prebuild).',
    '',
    'export const CAREPLAN_PROFILE_URLS = [',
    // Single-quoted to satisfy the repo's @stylistic/quotes rule — this file is
    // emitted into src/ and therefore linted.
    ...urls.map((u) => `  '${u.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}',`),
    '] as const',
    '',
    'export type CarePlanProfileUrl = (typeof CAREPLAN_PROFILE_URLS)[number]',
    '',
  ]
  // `recursive: true` is idempotent — guards against the rare case where
  // the catalog directory has been deleted (e.g., partial clone, manual rm).
  mkdirSync(destDir, { recursive: true })
  writeFileSync(outPath, lines.join('\n'), 'utf8')
  log(`emitted ${outPath.replace(repoRoot + '/', '')} with ${urls.length} CarePlan profile URL(s)`)
}

/**
 * Emit a TypeScript lookup of `canonical → linkId → the codings that
 * Questionnaire item declares`, read out of the hand-authored Questionnaire JSON
 * in FHIR-Resources/.
 *
 * Why: `packages/core/src/lib/observationMappers/fallbackDispatch.ts` recognizes
 * a foreign QuestionnaireResponse from standardized (LOINC) per-item codes. It
 * used to hand-list those codes — a third home for a value already living in the
 * Questionnaire and in the mappers — with `check-fallback-signatures.mjs`
 * existing solely to assert the copy still matched. Deriving the codes deletes
 * both the copy and the gate.
 *
 * What stays hand-authored, and why: the signature table's *curatorial*
 * decisions — which instruments get a signature at all, which linkIds belong to
 * each and in what order (Tier-3 positional mapping reads that order),
 * `minCodeMatches`, `answerKind`. Those are judgements with reasons recorded
 * beside them, and several are deliberate EXCLUSIONS of codes this file emits:
 * C-SSRS `actual-lethality`, the shared `risk-level` result code, and the whole
 * of ASQ. A generator that emitted signatures rather than a lookup would silently
 * put all three back. So this emits only the mechanical half — "what code does
 * this Questionnaire currently put on this linkId" — and `fallbackDispatch.ts`
 * names the linkIds it wants.
 *
 * Codes are emitted as an ARRAY per linkId because a Questionnaire item may carry
 * more than one (`item.code` is 0..*), which is also how the deleted gate modelled
 * it. No item in the repo carries two today; the consumer refuses to guess if one
 * ever does, rather than this script picking silently.
 */
function writeInstrumentItemCodes() {
  const stripVersion = (canonical) => {
    const pipe = canonical.indexOf('|')
    return pipe === -1 ? canonical : canonical.slice(0, pipe)
  }

  function* walkItems(items) {
    for (const it of items ?? []) {
      yield it
      yield* walkItems(it.item)
    }
  }

  // canonical (version-stripped) → Map(linkId → [{ system, code }]), for items
  // that carry a code at all. An item with no `code` contributes nothing: the
  // lookup answers "what standardized code names this item", and the answer for
  // an uncoded item is "none", not "an empty list".
  const byCanonical = new Map()
  const sourceOf = new Map()
  for (const file of walkFiles(questionnairesDir)) {
    if (!file.endsWith('.json')) continue
    let doc
    try {
      doc = JSON.parse(readFileSync(file, 'utf8'))
    } catch {
      continue // not JSON we can read — other gates own malformed FHIR
    }
    if (doc?.resourceType !== 'Questionnaire' || typeof doc.url !== 'string') continue
    const canonical = stripVersion(doc.url)
    const rel = file.replace(repoRoot + '/', '')
    if (byCanonical.has(canonical)) {
      // Two Questionnaires on one canonical is the #217 collision class; the
      // last writer would otherwise win in silence. See CLAUDE.md "One canonical
      // URL, one definition".
      console.error(
        `[copy-fhir] two Questionnaires declare canonical "${canonical}": ` +
          `${sourceOf.get(canonical)} and ${rel}`,
      )
      process.exit(1)
    }
    sourceOf.set(canonical, rel)

    const linkIdCodes = new Map()
    for (const it of walkItems(doc.item)) {
      if (!it.linkId) continue
      const codings = (it.code ?? [])
        .filter((c) => typeof c?.code === 'string')
        .map((c) => ({ system: typeof c.system === 'string' ? c.system : '', code: c.code }))
      if (codings.length) linkIdCodes.set(it.linkId, codings)
    }
    byCanonical.set(canonical, linkIdCodes)
  }

  if (byCanonical.size === 0) {
    // Reading nothing must not pass as "nothing to emit" — that is the #232/#261
    // failure mode, and here it would empty the lookup and take every signature's
    // itemCodes with it.
    console.error(
      `[copy-fhir] found no Questionnaires under ${questionnairesDir.replace(repoRoot + '/', '')} — refusing to emit an empty lookup`,
    )
    process.exit(1)
  }

  const q = (s) => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
  const lines = [
    '// Auto-generated by web/scripts/copy-fhir.mjs — do not edit by hand.',
    '// Source: FHIR-Resources/<tool>/*.json (Questionnaire.item[].code), keyed by',
    '// version-stripped Questionnaire.url.',
    '// Regenerated on every `npm run copy-fhir` (also runs as predev / prebuild).',
    '//',
    '// Consumed by packages/core/src/lib/observationMappers/fallbackDispatch.ts, which',
    '// names the linkIds each instrument signature covers and resolves their codes',
    '// here. The curatorial decisions — which instruments, which linkIds, in what',
    '// order — live there, not in this file.',
    '',
    'export const QUESTIONNAIRE_ITEM_CODES = {',
  ]
  let itemCount = 0
  for (const canonical of [...byCanonical.keys()].sort()) {
    const linkIdCodes = byCanonical.get(canonical)
    // A Questionnaire whose items carry no codes at all still appears, so the
    // absence is visible rather than looking like a Questionnaire this script
    // failed to read. Its `CodedLinkId` is `never`, so a signature cannot name
    // one of its linkIds.
    if (linkIdCodes.size === 0) {
      lines.push(`  ${q(canonical)}: {},`)
      continue
    }
    lines.push(`  ${q(canonical)}: {`)
    for (const linkId of [...linkIdCodes.keys()].sort()) {
      const codings = linkIdCodes
        .get(linkId)
        .map((c) => `{ system: ${q(c.system)}, code: ${q(c.code)} }`)
        .join(', ')
      lines.push(`    ${q(linkId)}: [${codings}],`)
      itemCount += 1
    }
    lines.push('  },')
  }
  lines.push(
    '} as const',
    '',
    '/** A Questionnaire canonical this lookup knows about. */',
    'export type QuestionnaireCanonical = keyof typeof QUESTIONNAIRE_ITEM_CODES',
    '',
    '/**',
    ' * A linkId that carries a code on the Questionnaire at `C`. Naming one that',
    ' * does not is a type error at every call site — which is what replaced the',
    ' * deleted check:fallback gate.',
    ' */',
    'export type CodedLinkId<C extends QuestionnaireCanonical> =',
    '  keyof (typeof QUESTIONNAIRE_ITEM_CODES)[C] & string',
    '',
  )

  mkdirSync(destDir, { recursive: true })
  writeFileSync(instrumentSignaturesTsPath, lines.join('\n'), 'utf8')
  log(
    `emitted ${instrumentSignaturesTsPath.replace(repoRoot + '/', '')} with ` +
      `${itemCount} coded item(s) across ${byCanonical.size} Questionnaire(s)`,
  )
}

/**
 * Emit a literal-union type of SPiER pathway stage ids, read out of the
 * compiled `SPiERPathwayStage` CodeSystem (`ig/input/fsh/spier-codesystem.fsh`
 * is the source of truth; SUSHI compiles it to
 * `CodeSystem-spier-pathway-stage.json`, already copied into `destDir` by
 * `copyResources()` above by the time this runs).
 *
 * Why: several hand-authored TypeScript tables key or value on a stage id
 * (`CAREPLAN_PROFILE_STAGES`, `STAGE_BLURB`, `StageTrigger.fromStageId` /
 * `toStageId`, `Tool.stageId`) and were typed as bare `string`, so a typo in
 * one of them was invisible at compile time. This is the same fix as
 * `writeCarePlanProfileTypes()` above, one level over: a generated union lets
 * those tables catch a typo AND a missing entry for a newly-added stage as a
 * compile error instead of silent wrong behavior.
 */
function writeStageIdType() {
  const codeSystemPath = join(destDir, 'CodeSystem-spier-pathway-stage.json')
  if (!existsSync(codeSystemPath)) {
    console.error(`[copy-fhir] expected ${codeSystemPath.replace(repoRoot + '/', '')} to exist — refusing to emit stage-ids.generated.ts`)
    process.exit(1)
  }

  let doc
  try {
    doc = JSON.parse(readFileSync(codeSystemPath, 'utf8'))
  } catch (err) {
    console.error(`[copy-fhir] ${codeSystemPath.replace(repoRoot + '/', '')} is not valid JSON: ${err.message}`)
    process.exit(1)
  }

  const concepts = Array.isArray(doc?.concept) ? doc.concept : []
  const codes = concepts.filter((c) => typeof c?.code === 'string').map((c) => c.code)
  if (codes.length === 0) {
    // Reading nothing must not pass as "nothing to emit" — the #232/#261
    // failure mode: every consumer of StageId would end up with `never`,
    // which would fail loudly elsewhere, but only after silently emitting an
    // empty union here first.
    console.error(
      `[copy-fhir] ${codeSystemPath.replace(repoRoot + '/', '')} has zero concept entries — refusing to emit an empty StageId union`,
    )
    process.exit(1)
  }

  const q = (s) => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
  const lines = [
    '// Auto-generated by web/scripts/copy-fhir.mjs — do not edit by hand.',
    '// Source: ig/input/fsh/spier-codesystem.fsh (CodeSystem: SPiERPathwayStage).',
    '// Regenerated on every `npm run copy-fhir` (also runs as predev / prebuild).',
    '',
    'export const STAGE_IDS = [',
    ...codes.map((c) => `  ${q(c)},`),
    '] as const',
    '',
    'export type StageId = (typeof STAGE_IDS)[number]',
    '',
    '/** Type guard for deriving a StageId from a plain string that is not already known-safe. */',
    'export function isStageId(x: string): x is StageId {',
    '  return (STAGE_IDS as readonly string[]).includes(x)',
    '}',
    '',
  ]

  mkdirSync(destDir, { recursive: true })
  writeFileSync(stageIdsTsPath, lines.join('\n'), 'utf8')
  log(`emitted ${stageIdsTsPath.replace(repoRoot + '/', '')} with ${codes.length} stage id(s)`)
}

const force = process.argv.includes('--force')
/**
 * Copy an ALREADY-COMPILED ig/fsh-generated into packages/fhir-artifacts/generated/, without
 * invoking sushi.
 *
 * For CI jobs that download `fsh-generated` as an artifact — ig.yml's `validate`
 * job does exactly that, and its own comment says the point is to "reuse the
 * compile from the `sushi` job rather than paying for it twice". Added for #302,
 * whose runtime emitter imports the generated CodeSystems and so needs the copy
 * step, but has no reason to recompile.
 */
const noCompile = process.argv.includes('--no-compile')
if (noCompile) {
  if (!existsSync(generatedDir)) {
    console.error(
      `[copy-fhir] --no-compile needs ${generatedDir.replace(repoRoot + '/', '')} to exist ` +
        'already (download the fsh-generated artifact, or drop --no-compile).',
    )
    process.exit(1)
  }
  clearDest()
  copyResources()
  writeCarePlanProfileTypes()
  writeInstrumentItemCodes()
  writeStageIdType()
  process.exit(0)
}
if (!force && isUpToDate()) {
  log('FHIR artifacts are up to date with their sources — skipping SUSHI compile.')
  log('(Edit any .fsh, sushi-config.yaml or FHIR-Resources/ file to trigger a rebuild, or run with --force.)')
  process.exit(0)
}

runSushi()
clearDest()
copyResources()
writeCarePlanProfileTypes()
writeInstrumentItemCodes()
writeStageIdType()
