#!/usr/bin/env node
// Compiles the FSH IG with Sushi, then copies the generated resource JSON
// into web/src/data/fhir/ so the React app can import FHIR resources directly.
//
// FSH is the single source of truth for SPiER's FHIR shapes. Anything under
// web/src/data/fhir/ is a build artifact — gitignored, regenerated by this
// script via `npm run copy-fhir` (also invoked by `predev` / `prebuild`).

import { spawnSync } from 'node:child_process'
import { mkdirSync, readdirSync, copyFileSync, readFileSync, writeFileSync, rmSync, statSync } from 'node:fs'
import { dirname, resolve, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(__dirname, '..', '..')
const igDir = join(repoRoot, 'ig')
const generatedDir = join(igDir, 'fsh-generated', 'resources')
const destDir = join(repoRoot, 'web', 'src', 'data', 'fhir')
const catalogDir = join(repoRoot, 'web', 'src', 'data', 'catalog')

// ImplementationGuide is IG manifest metadata, not a domain resource consumed by the app.
const EXCLUDE_PREFIXES = ['ImplementationGuide-']

function log(msg) {
  console.log(`[copy-fhir] ${msg}`)
}

function runSushi() {
  log('compiling FSH with sushi...')
  // Run from the script's cwd (web/ when invoked via `npm run`) so npx finds
  // the local fsh-sushi in web/node_modules/.bin. Pass igDir as an argument
  // — sushi treats it as the project folder and writes to ig/fsh-generated/.
  const result = spawnSync('npx', ['--no-install', 'fsh-sushi', igDir], {
    stdio: 'inherit',
    shell: process.platform === 'win32',
  })
  if (result.status !== 0) {
    console.error('[copy-fhir] sushi failed — aborting copy')
    process.exit(result.status ?? 1)
  }
}

function clearDest() {
  try {
    rmSync(destDir, { recursive: true, force: true })
  } catch {
    // ignore
  }
  mkdirSync(destDir, { recursive: true })
}

function copyResources() {
  let entries
  try {
    entries = readdirSync(generatedDir)
  } catch (err) {
    console.error(`[copy-fhir] expected ${generatedDir} to exist after sushi; got ${err.message}`)
    process.exit(1)
  }

  let copied = 0
  let skipped = 0
  for (const name of entries) {
    if (!name.endsWith('.json')) continue
    if (EXCLUDE_PREFIXES.some((p) => name.startsWith(p))) {
      skipped += 1
      continue
    }
    const src = join(generatedDir, name)
    if (!statSync(src).isFile()) continue
    copyFileSync(src, join(destDir, name))
    copied += 1
  }
  log(`copied ${copied} resource(s) to web/src/data/fhir/ (skipped ${skipped})`)
}

/**
 * Emit a TypeScript file declaring the union of canonical URLs for every
 * SPiER StructureDefinition that constrains CarePlan. The CarePlan mappers
 * use this union to type their `meta.profile` claim — FSH stays the single
 * source of truth.
 */
function writeCarePlanProfileTypes() {
  const sdFiles = readdirSync(destDir).filter(
    (n) => n.startsWith('StructureDefinition-') && n.endsWith('.json'),
  )
  const urls = []
  for (const name of sdFiles) {
    const doc = JSON.parse(readFileSync(join(destDir, name), 'utf8'))
    if (doc.kind === 'resource' && doc.type === 'CarePlan' && typeof doc.url === 'string') {
      urls.push(doc.url)
    }
  }
  urls.sort()

  const outPath = join(catalogDir, 'care-plan-profiles.generated.ts')
  const lines = [
    '// Auto-generated by web/scripts/copy-fhir.mjs — do not edit by hand.',
    '// Source: ig/input/fsh/<tool>.fsh (Profile: ... Parent: CarePlan).',
    '// Regenerated on every `npm run copy-fhir` (also runs as predev / prebuild).',
    '',
    'export const CAREPLAN_PROFILE_URLS = [',
    ...urls.map((u) => `  ${JSON.stringify(u)},`),
    '] as const',
    '',
    'export type CarePlanProfileUrl = (typeof CAREPLAN_PROFILE_URLS)[number]',
    '',
  ]
  writeFileSync(outPath, lines.join('\n'), 'utf8')
  log(`emitted ${outPath.replace(repoRoot + '/', '')} with ${urls.length} CarePlan profile URL(s)`)
}

runSushi()
clearDest()
copyResources()
writeCarePlanProfileTypes()
