/**
 * documentReference — the Tier-0 floor of the writeback ladder.
 *
 * Every server that speaks FHIR can store a DocumentReference, so this is the
 * universal fallback: it carries TWO attachments —
 *   1. a human-readable HTML rendering of the completed instrument (question
 *      text + answers + the derived risk summary), so a clinician can read the
 *      result in any EHR document viewer; and
 *   2. the raw QuestionnaireResponse JSON, base64-encoded, so the discrete data
 *      is recoverable later even on a server that couldn't ingest it discretely.
 *
 * Pure + dependency-free so it unit-tests cleanly.
 */
import type { FhirResource, QuestionnaireResponseResource, QuestionnaireResponseItem } from '../../types/fhir'
import type { RiskAlert } from '../observationMappers'

/** UTF-8-safe base64 (btoa is Latin1-only; JSON can carry non-ASCII). */
export function base64Utf8(input: string): string {
  const bytes = new TextEncoder().encode(input)
  let binary = ''
  for (const b of bytes) binary += String.fromCharCode(b)
  return btoa(binary)
}

const escapeHtml = (s: string): string =>
  s.replace(/[&<>"']/g, c =>
    c === '&' ? '&amp;'
    : c === '<' ? '&lt;'
    : c === '>' ? '&gt;'
    : c === '"' ? '&quot;'
    : '&#39;',
  )

/** Render the first answer of a QR item as display text. */
function answerText(item: QuestionnaireResponseItem): string {
  const answers = item.answer ?? []
  if (answers.length === 0) return '—'
  return answers
    .map(a => {
      if (a.valueCoding) return a.valueCoding.display ?? a.valueCoding.code ?? '—'
      if (typeof a.valueBoolean === 'boolean') return a.valueBoolean ? 'Yes' : 'No'
      if (typeof a.valueInteger === 'number') return String(a.valueInteger)
      if (typeof a.valueDecimal === 'number') return String(a.valueDecimal)
      if (a.valueString != null) return a.valueString
      if (a.valueText != null) return a.valueText
      if (a.valueDate != null) return a.valueDate
      return '—'
    })
    .join(', ')
}

/** Flatten QR items (recursing into nested item/answer.item) to question/answer rows. */
function flattenRows(items: QuestionnaireResponseItem[], rows: Array<{ q: string; a: string }> = []): Array<{ q: string; a: string }> {
  for (const item of items) {
    const hasAnswer = (item.answer?.length ?? 0) > 0
    if (hasAnswer || !item.item) {
      rows.push({ q: item.text ?? item.linkId ?? '(unlabeled)', a: answerText(item) })
    }
    if (item.item) flattenRows(item.item, rows)
    for (const ans of item.answer ?? []) {
      if (ans.item) flattenRows(ans.item, rows)
    }
  }
  return rows
}

/**
 * Build the human-readable HTML narrative for the Tier-0 attachment. Exported
 * for direct testing.
 */
export function renderQrNarrative(
  qr: QuestionnaireResponseResource,
  opts: { title?: string; riskAlert?: RiskAlert | null } = {},
): string {
  const title = escapeHtml(opts.title ?? 'Completed assessment')
  const rows = flattenRows(qr.item ?? [])
    .map(r => `<tr><td>${escapeHtml(r.q)}</td><td>${escapeHtml(r.a)}</td></tr>`)
    .join('')
  const authored = qr.authored ? `<p>Completed: ${escapeHtml(qr.authored)}</p>` : ''
  const summary = opts.riskAlert
    ? `<h2>Summary</h2><p><strong>${escapeHtml(opts.riskAlert.summary)}</strong></p><p>${escapeHtml(opts.riskAlert.detail)}</p>`
    : ''
  return [
    `<div xmlns="http://www.w3.org/1999/xhtml">`,
    `<h1>${title}</h1>`,
    authored,
    summary,
    `<h2>Responses</h2>`,
    `<table><thead><tr><th>Question</th><th>Answer</th></tr></thead><tbody>${rows}</tbody></table>`,
    `<p><em>Generated by the SPiER SMART app as the Tier-0 writeback floor. The raw QuestionnaireResponse is attached as recoverable FHIR JSON.</em></p>`,
    `</div>`,
  ].join('')
}

/**
 * Build the Tier-0 DocumentReference for a completed instrument.
 *
 * `qr` is the QuestionnaireResponse being written back; `patientId` scopes the
 * subject; `title`/`riskAlert` enrich the human-readable rendering.
 */
export function buildDocumentReference(params: {
  qr: QuestionnaireResponseResource
  patientId: string
  title?: string
  riskAlert?: RiskAlert | null
  /** ISO timestamp for DocumentReference.date; defaults to the QR's authored time. */
  date?: string
}): FhirResource {
  const { qr, patientId } = params
  const html = renderQrNarrative(qr, { title: params.title, riskAlert: params.riskAlert })
  const rawJson = JSON.stringify(qr)
  const date = params.date ?? qr.authored

  return {
    resourceType: 'DocumentReference',
    status: 'current',
    // US Core document category — a clinical note. type is left text-only:
    // there is no single normative LOINC "completed screening questionnaire"
    // document code we can assert without risk, so we describe it in text.
    type: {
      text: params.title
        ? `${params.title} — completed assessment`
        : 'Completed assessment questionnaire response',
    },
    category: [
      {
        coding: [
          {
            system: 'http://hl7.org/fhir/us/core/CodeSystem/us-core-documentreference-category',
            code: 'clinical-note',
            display: 'Clinical Note',
          },
        ],
      },
    ],
    subject: { reference: `Patient/${patientId}` },
    ...(date ? { date } : {}),
    description:
      'SPiER SMART app writeback floor (Tier 0): human-readable rendering plus the raw QuestionnaireResponse JSON for later discrete recovery.',
    content: [
      {
        attachment: {
          contentType: 'text/html',
          data: base64Utf8(html),
          title: params.title ? `${params.title} (rendering)` : 'Assessment rendering',
        },
      },
      {
        attachment: {
          contentType: 'application/fhir+json',
          data: base64Utf8(rawJson),
          title: 'QuestionnaireResponse (FHIR JSON)',
        },
      },
    ],
  }
}
