/**
 * Shared readers for `ig/sushi-config.yaml` and the IG's page tree.
 *
 * Extracted from `check-ig-menu.mjs` when `check-ig-narrative.mjs` (task C1)
 * needed the same `pages:` block and the same GENERATED_PAGES allowlist. Two
 * readers of one file is the shape this repo keeps catching one layer up; two
 * *gates* sharing one reader is the fix.
 *
 * Every parser here **bails rather than skips** on a form it cannot read. A
 * quiet parse failure is how a gate reports green over a file it never read —
 * #232, #261, and the reason `web/scripts/lib/vite-alias.mjs` throws too. A
 * missing block, or zero entries parsed, is an error and not a pass.
 *
 * Node 20: every workflow pins it, and this repo has already shipped two gates
 * that threw in CI on Node 22-only syntax.
 */

import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))

export const ROOT = resolve(here, '../..')
export const CONFIG = resolve(ROOT, 'ig/sushi-config.yaml')
export const PAGECONTENT = resolve(ROOT, 'ig/input/pagecontent')
export const FSH_GENERATED = resolve(ROOT, 'ig/fsh-generated/resources')

export const rel = (p) => p.slice(ROOT.length + 1)

/**
 * Menu and link targets with no `pagecontent/*.md` behind them, and why each is
 * legitimate. Verified against the rendered IG, not assumed — `artifacts.html`
 * is 200 and `downloads.html` is 404 under `fhir.base.template#current`. Add an
 * entry only after confirming the publisher really emits the page.
 */
export const GENERATED_PAGES = {
  'artifacts.html': 'generated by the IG Publisher from the ImplementationGuide resource',
}

/**
 * Build a `bail` that names the calling gate. Failing the whole run is the
 * point: a parse we cannot trust must never degrade to a pass.
 */
export function makeBail(gate) {
  return function bail(message) {
    console.error(`\n✗ ${gate}: ${message}\n`)
    process.exit(1)
  }
}

export const readConfig = () => readFileSync(CONFIG, 'utf8')

/**
 * Parse the `pages:` block out of sushi-config.yaml.
 *
 * A deliberately strict two-level block-map reader rather than a YAML
 * dependency (there is no root package.json). This block decides which pages
 * exist at all, so a form we cannot read must fail rather than parse as empty.
 * Shape is `  <name>.md:` followed by indented `title: …` keys.
 */
export function parsePages(text, bail) {
  const lines = text.split('\n')
  const start = lines.findIndex((l) => /^pages:\s*$/.test(l))
  if (start === -1) bail(`no \`pages:\` block in ${rel(CONFIG)} — nothing to compare the menu against`)

  /** @type {string[]} */
  const pages = []

  for (let i = start + 1; i < lines.length; i++) {
    const line = lines[i]
    if (line.trim() === '' || /^\s*#/.test(line)) continue
    if (/^\S/.test(line)) break // dedent to column 0 ends the block

    const top = /^ {2}(\S.*?)\s*$/.exec(line)
    const child = /^ {4}(\S.*?)\s*$/.exec(line)

    if (top) {
      const m = /^(.+?):\s*$/.exec(top[1])
      if (!m) bail(`unparseable \`pages:\` line in ${rel(CONFIG)}:${i + 1} — ${line.trim()}`)
      if (!/^[\w-]+\.md$/.test(m[1])) {
        bail(`\`pages:\` key at ${rel(CONFIG)}:${i + 1} is not a local \`*.md\` page — ${m[1]}`)
      }
      pages.push(m[1])
    } else if (child) {
      if (pages.length === 0) bail(`indented \`pages:\` entry with no parent at ${rel(CONFIG)}:${i + 1}`)
      if (!/^\w+:\s+\S/.test(child[1])) {
        bail(`unparseable \`pages:\` property at ${rel(CONFIG)}:${i + 1} — ${line.trim()}`)
      }
    } else {
      bail(`unexpected indentation in \`pages:\` at ${rel(CONFIG)}:${i + 1} — ${JSON.stringify(line)}`)
    }
  }

  if (pages.length === 0) bail(`parsed 0 entries from \`pages:\` in ${rel(CONFIG)} — refusing to pass vacuously`)
  return pages
}

/**
 * Parse the `parameters.path-resource:` list out of sushi-config.yaml — the
 * directories of hand-authored resources the publisher loads alongside SUSHI's
 * output.
 *
 * ⚠️ This is what makes the five FML StructureMaps resolvable. They are NOT in
 * `fsh-generated/`: they are hand-authored FHIR Mapping Language under
 * `input/resources/maps/`, reaching the build through this one config line
 * (#92 / #229). A link checker that indexed only `fsh-generated/` would call
 * all five StructureMap pages broken, and the natural "fix" — deleting the
 * links — would remove the guide's only navigation to its own transformations.
 *
 * Read from the config rather than hardcoded, so adding a `path-resource`
 * directory does not require editing a gate.
 */
export function parsePathResource(text, bail) {
  const lines = text.split('\n')
  const start = lines.findIndex((l) => /^\s{2}path-resource:\s*$/.test(l))
  if (start === -1) return [] // legitimately absent: an IG may have no hand-authored resources

  /** @type {string[]} */
  const dirs = []
  for (let i = start + 1; i < lines.length; i++) {
    const line = lines[i]
    if (line.trim() === '' || /^\s*#/.test(line)) continue
    const item = /^\s{4}-\s+(\S.*?)\s*$/.exec(line)
    if (!item) break // end of the sequence (a sibling key, or a dedent)
    if (/["'|>&*]/.test(item[1])) {
      bail(`\`path-resource\` item at ${rel(CONFIG)}:${i + 1} uses YAML syntax this parser does not read — ${item[1]}`)
    }
    dirs.push(item[1])
  }

  if (dirs.length === 0) {
    bail(
      `\`path-resource:\` is declared in ${rel(CONFIG)} but parsed 0 directories — refusing to pass ` +
        `vacuously over resources the publisher does load`,
    )
  }
  return dirs
}
