/**
 * conditionProposal — the Tier-3 (opt-in, default OFF) proposal builder.
 *
 * A screener score is an Observation; a problem-list Condition is a clinical
 * assertion that is patient-visible under information-blocking rules. The app
 * therefore never auto-writes a Condition: it only *proposes* one, and a human
 * must explicitly confirm in the UI (Phase 2) before it is sent. This module
 * just builds the proposed resource; enabling the tier and gating the write are
 * the caller's responsibility.
 *
 * The proposed Condition is stamped `verificationStatus = unconfirmed` — the
 * FHIR-correct signal that this is a screening-derived, not-yet-verified
 * assertion — which reinforces the governance caveat in the data itself.
 *
 * Codes come from the concept-harmonization layer, not invented here:
 *   Condition.code uses the SPiER Suicide Risk Tier CodeSystem
 *   (ig/input/fsh/concept-layer.fsh). ⚠️ These tier codes are hand-duplicated
 *   across ig/ and web/ — if you change them, grep the whole repo (see CLAUDE.md).
 */
import type { FhirResource } from '../../types/fhir'
import type { RiskAlert } from '../observationMappers'

/** Canonical URL of the SPiER Suicide Risk Tier CodeSystem (concept-layer.fsh). */
export const SPIER_RISK_TIER_SYSTEM = 'http://spier.org/CodeSystem/spier-suicide-risk-tier'

/** One SPiER suicide-risk tier code + display (concept-layer.fsh). */
interface RiskTier {
  code: string
  display: string
}

/**
 * Map the runtime RiskAlert.level onto a SPiER suicide-risk tier. The alert's
 * vocabulary (`none/low/moderate/high/acute`) differs from the harmonized tier
 * vocabulary (`no-risk/low/moderate/high/imminent`) at the two ends — this is
 * the single crosswalk point between them.
 */
export function riskAlertLevelToTier(level: RiskAlert['level']): RiskTier {
  switch (level) {
    case 'none': return { code: 'no-risk', display: 'No risk identified' }
    case 'low': return { code: 'low', display: 'Low risk' }
    case 'moderate': return { code: 'moderate', display: 'Moderate risk' }
    case 'high': return { code: 'high', display: 'High risk' }
    case 'acute': return { code: 'imminent', display: 'Imminent risk' }
  }
}

/**
 * Build a *proposed* problem-list Condition from a derived risk alert, or
 * `null` when no problem is warranted.
 *
 * Returns `null` for a negative screen (`none` → `no-risk`): the app does not
 * propose a problem-list entry for a patient who screened negative.
 *
 * `derivedFromRefs` are references (e.g. `QuestionnaireResponse/123`,
 * `Observation/456`) recorded as `Condition.evidence`, so the proposal carries
 * its provenance. At build time these may point at client-minted ids; the
 * executor remaps them to server ids after the QR is created.
 */
export function buildConditionProposal(params: {
  riskAlert: RiskAlert
  patientId: string
  derivedFromRefs?: string[]
  /** ISO timestamp for Condition.recordedDate; defaults to now at call time. */
  recordedDate?: string
}): FhirResource | null {
  const tier = riskAlertLevelToTier(params.riskAlert.level)
  if (tier.code === 'no-risk') return null

  const evidence = (params.derivedFromRefs ?? []).filter(Boolean)

  return {
    resourceType: 'Condition',
    clinicalStatus: {
      coding: [
        {
          system: 'http://terminology.hl7.org/CodeSystem/condition-clinical',
          code: 'active',
          display: 'Active',
        },
      ],
    },
    // The governance-critical flag: this is a screening-derived assertion that
    // has NOT been verified by a clinician.
    verificationStatus: {
      coding: [
        {
          system: 'http://terminology.hl7.org/CodeSystem/condition-ver-status',
          code: 'unconfirmed',
          display: 'Unconfirmed',
        },
      ],
    },
    category: [
      {
        coding: [
          {
            system: 'http://terminology.hl7.org/CodeSystem/condition-category',
            code: 'problem-list-item',
            display: 'Problem List Item',
          },
        ],
      },
    ],
    code: {
      coding: [{ system: SPIER_RISK_TIER_SYSTEM, code: tier.code, display: tier.display }],
      text: `Elevated suicide risk — ${tier.display.toLowerCase()} (${params.riskAlert.tool}, screening-derived)`,
    },
    subject: { reference: `Patient/${params.patientId}` },
    ...(evidence.length ? { evidence: [{ detail: evidence.map(reference => ({ reference })) }] } : {}),
    ...(params.recordedDate ? { recordedDate: params.recordedDate } : {}),
    note: [
      {
        text:
          `PROPOSED problem-list entry derived from a ${params.riskAlert.tool} suicide-risk screen. ` +
          'Recorded as unconfirmed — it requires clinician verification before it is treated as an established problem. ' +
          'Generated by the SPiER SMART app (proof of concept).',
      },
    ],
  }
}
