#!/usr/bin/env node
/**
 * IG menu gate — `how-to-read.md` describes the guide's navigation in prose, and
 * `sushi-config.yaml` defines it. Nothing compared the two.
 *
 * ─── Why this exists ─────────────────────────────────────────────────────────
 *
 * `ig/input/pagecontent/how-to-read.md`'s "## The menu" section restates
 * `ig/sushi-config.yaml`'s `menu:` block by hand — the hand-duplicated-constant
 * shape this repo keeps catching, one layer up from code. It had already drifted
 * twice before this gate existed: once with two live entries missing from the
 * prose, and once (#409) with a **Downloads** bullet describing a menu entry and
 * a page that do not exist. `fhir.base.template#current` emits no
 * `downloads.html` — that is a US Core template convention — so `/ig/downloads.html`
 * was a 404 while the prose sent readers looking for it.
 *
 * The IG Publisher could not see either drift. Its broken-link check only sees
 * links that exist, and a bullet *describing* a menu entry is not a link. There
 * was no relationship between the two files that any tool could read.
 *
 * ─── Why it lives here and not in `web`'s verify ─────────────────────────────
 *
 * Both inputs are under `ig/`, like `check-sushi-output.mjs` and `check-fml.mjs`.
 * `ig.yml` triggers on `ig/**`; `web-lint.yml` does not, so a `sushi-config.yaml`-only
 * edit would leave a `web`-hosted gate idle for exactly the change that breaks it.
 * It needs no dependencies and no SUSHI compile, so it runs in milliseconds.
 *
 * ─── What it asserts ─────────────────────────────────────────────────────────
 *
 *   A. The top-level entry sets agree, in BOTH directions — every `menu:` key is
 *      a bolded bullet, and every bolded bullet is a `menu:` key.
 *   B. Per entry, the `.html` links inside its bullet are exactly right: a parent
 *      must link every child it declares, and no bullet may link a page that
 *      entry does not point at.
 *   C. Every `menu:` target resolves to a real `input/pagecontent/<name>.md`, or
 *      is a page the IG Publisher generates (allowlist with reasons, below).
 *      This is what stops the drift being "fixed" in the wrong direction — adding
 *      `Downloads: downloads.html` to `menu:` would satisfy A and B and ship a
 *      broken link.
 *   D. `menu:` and `pages:` agree, in BOTH directions. A page needs both blocks
 *      and they do different jobs: `menu:` makes it reachable, `pages:` is what
 *      makes the publisher render it at all. Checks A–C could not see the gap,
 *      because the `.md` file genuinely exists — C looks at the filesystem, and
 *      SUSHI compiles clean either way.
 *
 *      The cost is not one broken link. The menu is rendered onto EVERY page, so
 *      a menu target the publisher never renders is one broken link per page:
 *      adding `Care Pathway: care-pathway.html` to `menu:` alone took this IG
 *      from 0 to **1812** broken links, with `err = 0` and a green SUSHI run,
 *      and the `publish` job's broken-link gate was the only thing that caught
 *      it. The reverse direction is the milder defect of the same shape — a page
 *      the publisher renders that nothing navigates to.
 *
 * Reading nothing is an ERROR, not a pass (#232, #261, and four more since): a
 * missing `menu:` block, a missing "## The menu" section, or zero entries parsed
 * on either side fails. So does any YAML or bullet form the parsers do not
 * understand — a quiet parse failure is how a gate reports green over a file it
 * never read, which is the same rule `web/scripts/lib/vite-alias.mjs` follows.
 *
 * Node 20 is part of the contract: every workflow pins it, and this repo has
 * already shipped two gates that threw in CI on Node 22-only syntax
 * (`fs.globSync`, `Iterator.prototype.map`).
 */

import { readFileSync, existsSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(here, '..')
const CONFIG = resolve(ROOT, 'ig/sushi-config.yaml')
const DOC = resolve(ROOT, 'ig/input/pagecontent/how-to-read.md')
const PAGECONTENT = resolve(ROOT, 'ig/input/pagecontent')

/**
 * Menu targets with no `pagecontent/*.md` behind them, and why each is legitimate.
 * Verified against the rendered IG, not assumed — `artifacts.html` is 200 and
 * `downloads.html` is 404 under `fhir.base.template#current`. Add an entry only
 * after confirming the publisher really emits the page.
 */
const GENERATED_PAGES = {
  'artifacts.html': 'generated by the IG Publisher from the ImplementationGuide resource',
}

/**
 * The page the prose itself lives on. Its bullet says "this page" rather than
 * linking `how-to-read.html`, so it is exempt from check B's link requirement.
 *
 * ⚠️ The limit of that exemption, stated rather than left implicit: if this page
 * moved to a different parent in `menu:`, the prose could keep describing it
 * under the old one and only check B's *link* half would notice. What is still
 * asserted is that it appears in the menu at all — a page that describes the
 * menu and is not in it is the drift this gate exists for.
 */
const SELF_PAGE = 'how-to-read.html'

/**
 * Pages the publisher renders that the menu deliberately does not navigate to,
 * and why each is legitimate — check D's reverse direction. Empty today, and
 * that is the finding: every page this IG renders is reachable from its menu.
 * A page reached only from body text would belong here, with the page that
 * links it named.
 *
 * @type {Record<string, string>}
 */
const UNLISTED_PAGES = {}

const rel = (p) => p.slice(ROOT.length + 1)

/** Fail the whole run — a parse we cannot trust must never degrade to a pass. */
function bail(message) {
  console.error(`\n✗ check-ig-menu: ${message}\n`)
  process.exit(1)
}

// --- Parse `menu:` out of sushi-config.yaml ---------------------------------
//
// A deliberately strict two-level block-map reader rather than a YAML dependency
// (there is no root package.json). It throws on any form it does not understand,
// so an unreadable menu fails loudly instead of parsing as empty.
function parseMenu(text) {
  const lines = text.split('\n')
  const start = lines.findIndex((l) => /^menu:\s*$/.test(l))
  if (start === -1) bail(`no \`menu:\` block in ${rel(CONFIG)} — nothing to compare against`)

  /** @type {{ key: string, target: string | null, children: Map<string, string> }[]} */
  const entries = []

  for (let i = start + 1; i < lines.length; i++) {
    const line = lines[i]
    if (line.trim() === '' || /^\s*#/.test(line)) continue
    if (/^\S/.test(line)) break // dedent to column 0 ends the block

    const top = /^ {2}(\S.*?)\s*$/.exec(line)
    const child = /^ {4}(\S.*?)\s*$/.exec(line)

    if (top) {
      const m = /^(.+?):(?:\s+(.*))?$/.exec(top[1])
      if (!m) bail(`unparseable \`menu:\` line in ${rel(CONFIG)}:${i + 1} — ${line.trim()}`)
      if (/["'|>&*]/.test(m[1])) {
        bail(`\`menu:\` key at ${rel(CONFIG)}:${i + 1} uses YAML syntax this parser does not read — ${m[1]}`)
      }
      entries.push({ key: m[1], target: m[2] ? m[2].trim() : null, children: new Map() })
    } else if (child) {
      const parent = entries[entries.length - 1]
      if (!parent) bail(`indented \`menu:\` entry with no parent at ${rel(CONFIG)}:${i + 1}`)
      if (parent.target) {
        bail(`\`menu:\` entry "${parent.key}" has both a target and children (${rel(CONFIG)}:${i + 1})`)
      }
      const m = /^(.+?):\s+(.+?)\s*$/.exec(child[1])
      if (!m) bail(`unparseable \`menu:\` child at ${rel(CONFIG)}:${i + 1} — ${line.trim()}`)
      parent.children.set(m[1], m[2])
    } else {
      bail(`unexpected indentation in \`menu:\` at ${rel(CONFIG)}:${i + 1} — ${JSON.stringify(line)}`)
    }
  }

  if (entries.length === 0) bail(`parsed 0 entries from \`menu:\` in ${rel(CONFIG)} — refusing to pass vacuously`)
  for (const e of entries) {
    if (!e.target && e.children.size === 0) bail(`\`menu:\` entry "${e.key}" has neither a target nor children`)
  }
  return entries
}

// --- Parse the "## The menu" bullets out of how-to-read.md ------------------
function parseProse(text) {
  const lines = text.split('\n')
  const start = lines.findIndex((l) => /^##\s+The menu\s*$/.test(l))
  if (start === -1) bail(`no \`## The menu\` section in ${rel(DOC)} — nothing to compare against`)

  /** @type {{ label: string, body: string, line: number }[]} */
  const bullets = []

  for (let i = start + 1; i < lines.length; i++) {
    const line = lines[i]
    if (/^##\s/.test(line)) break // next section ends it
    if (line.trim() === '') continue

    if (/^\s*[-*]\s/.test(line)) {
      const m = /^-\s+\*\*(.+?)\*\*\s*(.*)$/.exec(line)
      if (!m) {
        bail(
          `bullet at ${rel(DOC)}:${i + 1} is not the \`- **Name** — …\` form this gate reads.\n` +
            `    ${line.trim()}\n` +
            `    Every bullet under "## The menu" names a menu entry; an unreadable one would be skipped silently.`,
        )
      }
      bullets.push({ label: m[1], body: m[2], line: i + 1 })
    } else if (bullets.length > 0) {
      bullets[bullets.length - 1].body += ` ${line.trim()}` // wrapped continuation
    }
  }

  if (bullets.length === 0) bail(`parsed 0 bullets from \`## The menu\` in ${rel(DOC)} — refusing to pass vacuously`)
  return bullets
}

// --- Parse `pages:` out of sushi-config.yaml --------------------------------
//
// Same strictness as parseMenu, and the same reason: this block decides which
// pages exist at all, so a form we cannot read must fail rather than parse as
// empty. Shape is `  <name>.md:` followed by indented `title: …` keys.
function parsePages(text) {
  const lines = text.split('\n')
  const start = lines.findIndex((l) => /^pages:\s*$/.test(l))
  if (start === -1) bail(`no \`pages:\` block in ${rel(CONFIG)} — nothing to compare the menu against`)

  /** @type {string[]} */
  const pages = []

  for (let i = start + 1; i < lines.length; i++) {
    const line = lines[i]
    if (line.trim() === '' || /^\s*#/.test(line)) continue
    if (/^\S/.test(line)) break // dedent to column 0 ends the block

    const top = /^ {2}(\S.*?)\s*$/.exec(line)
    const child = /^ {4}(\S.*?)\s*$/.exec(line)

    if (top) {
      const m = /^(.+?):\s*$/.exec(top[1])
      if (!m) bail(`unparseable \`pages:\` line in ${rel(CONFIG)}:${i + 1} — ${line.trim()}`)
      if (!/^[\w-]+\.md$/.test(m[1])) {
        bail(`\`pages:\` key at ${rel(CONFIG)}:${i + 1} is not a local \`*.md\` page — ${m[1]}`)
      }
      pages.push(m[1])
    } else if (child) {
      if (pages.length === 0) bail(`indented \`pages:\` entry with no parent at ${rel(CONFIG)}:${i + 1}`)
      if (!/^\w+:\s+\S/.test(child[1])) {
        bail(`unparseable \`pages:\` property at ${rel(CONFIG)}:${i + 1} — ${line.trim()}`)
      }
    } else {
      bail(`unexpected indentation in \`pages:\` at ${rel(CONFIG)}:${i + 1} — ${JSON.stringify(line)}`)
    }
  }

  if (pages.length === 0) bail(`parsed 0 entries from \`pages:\` in ${rel(CONFIG)} — refusing to pass vacuously`)
  return pages
}

const menu = parseMenu(readFileSync(CONFIG, 'utf8'))
const bullets = parseProse(readFileSync(DOC, 'utf8'))
const pages = parsePages(readFileSync(CONFIG, 'utf8'))

const problems = []

// --- A. The top-level entry sets agree, both directions ---------------------
const menuKeys = menu.map((e) => e.key)
const proseLabels = bullets.map((b) => b.label)

for (const key of menuKeys) {
  if (!proseLabels.includes(key)) {
    problems.push(`\`menu:\` declares "${key}", but ${rel(DOC)}'s "## The menu" never describes it`)
  }
}
for (const b of bullets) {
  if (!menuKeys.includes(b.label)) {
    problems.push(
      `${rel(DOC)}:${b.line} describes a "${b.label}" menu entry that \`menu:\` does not declare — ` +
        `readers are sent to navigation that does not exist`,
    )
  }
}

// --- B. A bullet's links are exactly the pages that entry points at ---------
for (const b of bullets) {
  const entry = menu.find((e) => e.key === b.label)
  if (!entry) continue // already reported by check A

  const linked = new Set()
  for (const m of b.body.matchAll(/\[[^\]]*\]\(([^)]+\.html)\)/g)) linked.add(m[1])

  const allowed = entry.target ? new Set([entry.target]) : new Set(entry.children.values())
  const required = entry.target ? new Set() : new Set(entry.children.values())
  required.delete(SELF_PAGE) // "this page" — see SELF_PAGE

  for (const target of required) {
    if (!linked.has(target)) {
      const child = [...entry.children].find(([, t]) => t === target)?.[0]
      problems.push(`${rel(DOC)}:${b.line} — "${b.label}" does not link its child page "${child}" (${target})`)
    }
  }
  for (const target of linked) {
    if (!allowed.has(target)) {
      problems.push(
        `${rel(DOC)}:${b.line} — the "${b.label}" bullet links ${target}, which is not a page that entry points at`,
      )
    }
  }
}

// --- C. Every menu target is a real page ------------------------------------
const targets = []
for (const e of menu) {
  if (e.target) targets.push([e.key, e.target])
  for (const [k, t] of e.children) targets.push([`${e.key} › ${k}`, t])
}

if (!targets.some(([, t]) => t === SELF_PAGE)) {
  problems.push(
    `\`menu:\` does not point at ${SELF_PAGE} anywhere, but ${rel(DOC)} is that page and describes the menu — ` +
      `the guide's own map is no longer in the guide`,
  )
}

for (const [label, target] of targets) {
  if (GENERATED_PAGES[target]) continue
  if (!/^[\w-]+\.html$/.test(target)) {
    problems.push(`\`menu:\` entry "${label}" points at "${target}", which is not a local page`)
    continue
  }
  const source = resolve(PAGECONTENT, target.replace(/\.html$/, '.md'))
  if (!existsSync(source)) {
    problems.push(
      `\`menu:\` entry "${label}" points at ${target}, but ${rel(source)} does not exist ` +
        `and ${target} is not in GENERATED_PAGES — the menu would render a broken link`,
    )
  }
}

// --- D. `menu:` and `pages:` agree, both directions -------------------------
const pageSet = new Set(pages)
const menuPages = new Set()

for (const [label, target] of targets) {
  if (GENERATED_PAGES[target]) continue
  if (!/^[\w-]+\.html$/.test(target)) continue // already reported by check C
  const md = target.replace(/\.html$/, '.md')
  menuPages.add(md)
  if (!pageSet.has(md)) {
    problems.push(
      `\`menu:\` entry "${label}" points at ${target}, but ${md} is not in the \`pages:\` block — ` +
        'the publisher renders no such page, and the menu is on EVERY page, so this is one broken link ' +
        'per rendered page rather than one. A page needs both blocks.',
    )
  }
}

for (const md of pages) {
  if (menuPages.has(md)) continue
  if (UNLISTED_PAGES[md]) continue
  problems.push(
    `\`pages:\` renders ${md}, but no \`menu:\` entry navigates to ${md.replace(/\.md$/, '.html')} — ` +
      'the page ships unreachable. If that is intentional, add it to UNLISTED_PAGES in this script ' +
      'with the page that links it.',
  )
}

// --- Report -----------------------------------------------------------------
if (problems.length) {
  console.error(`\n✗ check-ig-menu: ${problems.length} problem(s):\n`)
  for (const p of problems) console.error(`  • ${p}`)
  console.error(
    `\n  \`menu:\` is the definition (${rel(CONFIG)}); "## The menu" in ${rel(DOC)} restates it for readers.\n` +
      `  Both have to change together.\n`,
  )
  process.exit(1)
}

const childCount = menu.reduce((n, e) => n + e.children.size, 0)
console.log(
  `✓ check-ig-menu: ${menu.length} menu entries (${childCount} sub-entries) agree between ` +
    `${rel(CONFIG)} and ${rel(DOC)}, and every target resolves to a page.`,
)
console.log(
  `  ${pages.length} \`pages:\` entries agree with \`menu:\` in both directions ` +
    `(${Object.keys(UNLISTED_PAGES).length} deliberately unlinked).`,
)
